### PR TITLE
fix(codex): don't skip closure or arrow function likes in incremental build

### LINKED ISSUE #1359: Types within a closure become unknown-refs on incremental builds in watch mode
### Description

When running an incremental build with `analyze --watch`, it appears that types used within anonymous functions end up with an `unknown_ref` type on incremental builds (after the initial build).

These changes seem to fix the issue, but I'm not sure if that's the right fix

```diff
diff --git a/crates/codex/src/populator/mod.rs b/crates/codex/src/populator/mod.rs
index 6f4dcc49..11e438b9 100644
--- a/crates/codex/src/populator/mod.rs
+++ b/crates/codex/src/populator/mod.rs
@@ -121,13 +121,6 @@ fn populate_codebase_inner(
     if let Some(dirty) = &dirty_symbols {
         for dirty_key in dirty {
             if let Some(function_like_metadata) = codebase.function_likes.get_mut(dirty_key) {
-                let is_closure_or_arrow = function_like_metadata.get_kind().is_closure()
-                    || function_like_metadata.get_kind().is_arrow_function();
-
-                if is_closure_or_arrow {
-                    continue;
-                }
-
                 let force_repopulation = function_like_metadata.flags.is_user_defined();
                 if function_like_metadata.flags.is_populated() && !force_repopulation {
                     continue;
diff --git a/crates/orchestrator/src/service/incremental_analysis.rs b/crates/orchestrator/src/service/incremental_analysis.rs
index 6363ea53..b03b441f 100644
--- a/crates/orchestrator/src/service/incremental_analysis.rs
+++ b/crates/orchestrator/src/service/incremental_analysis.rs
@@ -3801,4 +3801,45 @@ mod tests {
         service.analyze_incremental(None).expect("Incremental failed.");
         assert_matches_full(&service, &db, "both changed to be compatible");
     }
+
+    /// Body-only change in a file with a closure whose parameter references another class.
+    /// Reproduces a bug where closure/arrow function type references were never populated
+    /// in the targeted incremental path, leaving TReference::Symbol entries unresolved
+    /// and causing non-existent-class-like errors.
+    #[test]
+    fn test_watch_body_change_closure_with_typed_param() {
+        let exception_class = "<?php\nclass MyException extends \\Exception {\n    public function getDetails(): string { return 'details'; }\n}\n";
+        let service_v1 = concat!(
+            "<?php\nclass Service {\n",
+            "    public function run(): void {\n",
+            "        $handler = function(MyException $e): string {\n",
+            "            return $e->getDetails();\n",
+            "        };\n",
+            "    }\n",
+            "}\n",
+        );
+
+        let mut db = make_database(vec![
+            ("src/MyException.php", exception_class),
+            ("src/Service.php", service_v1),
+        ]);
+        let mut service = make_watch_service(&db);
+        service.analyze().expect("Initial analysis failed.");
+        assert_matches_full(&service, &db, "initial");
+
+        // Body-only change: modify the closure body but keep the signature identical.
+        let service_v2 = concat!(
+            "<?php\nclass Service {\n",
+            "    public function run(): void {\n",
+            "        $handler = function(MyException $e): string {\n",
+            "            return $e->getDetails() . ' extra';\n",
+            "        };\n",
+            "    }\n",
+            "}\n",
+        );
+        db.update(FileId::new("src/Service.php"), Cow::Owned(service_v2.to_string()));
+        service.update_database(db.read_only());
+        service.analyze_incremental(None).expect("Incremental failed.");
+        assert_matches_full(&service, &db, "body change in closure with typed param");
+    }
 }

```

### Playground Link

_No response_

### Reproduction

1. Create `Example.php`

```php
<?php

class Service
{
    public function run(): void
    {
        $handler = function (MyException $e): string {
            return $e->getDetails();
        };
    }
}

class MyException extends \Exception
{
    public function getDetails(): string
    {
        return "details";
    }
}
```

Run `mago analyze --watch` and get the following output (no errors)

```
 INFO Starting watch mode. Press Ctrl+C to stop.
 INFO Database watcher started for workspace: /Users/chrisopperwall/projects/mago/min_repro
 INFO Watching /Users/chrisopperwall/projects/mago/min_repro for changes...
 INFO Running initial analysis...
 INFO No issues found.
 INFO Initial analysis complete. Watching for changes...
```

Update Example.php to trigger an incremental build

```
INFO Detected 1 file change(s), re-analyzing...
error[non-existent-class-like]: Cannot find class, interface, enum, or type alias `MyException`.
  ┌─ MyServer.php:7:30
  │
7 │         $handler = function (MyException $e): string {
  │                              ^^^^^^^^^^^ `MyException` is not defined in the current codebase
  │
  = This error occurs when a type is referenced but not found in any analyzed source files or stubs.
  = If this type comes from an optional dependency or extension, you can safely suppress this issue using `@mago-ignore` or `@mago-expect`.
  = Help: Verify the type name is spelled correctly, the file containing it is included in analysis, and any required `use` statements are present.

error[invalid-method-access]: Attempting to access a method on a non-object type (`unknown-ref(MyException)`).
  ┌─ MyServer.php:8:24
  │
8 │             return $e->getDetails();
  │                    --  ^^^^^^^^^^ Cannot call method here
  │                    │
  │                    This expression has type `unknown-ref(MyException)`

error: found 2 issues: 2 error(s)

 INFO Analysis complete. Watching for changes...
```

Restart watcher process and observe that the errors are no longer there

```
 INFO Starting watch mode. Press Ctrl+C to stop.
 INFO Database watcher started for workspace: /Users/chrisopperwall/projects/mago/min_repro
 INFO Watching /Users/chrisopperwall/projects/mago/min_repro for changes...
 INFO Running initial analysis...
 INFO No issues found.
 INFO Initial analysis complete. Watching for changes...
```

### Environment

- Mago: main
- MacOS and Linux
- Compiled from source

### PR DESCRIPTION
**Pull request by chrisopperwall-qz**
## 📌 What Does This PR Do?

When running an incremental build with analyze --watch, it appears that types used within anonymous functions end up with an unknown_ref type on incremental builds (after the initial build). This fixes the issue by not skipping population of closure or arrow function likes on an incremental build.

## 🔍 Context & Motivation

This is fixing a bug when using `mago analyze --watch`

## 🛠️ Summary of Changes

- **Bug Fix:** don't skip closure or arrow function likes in incremental build

## 📂 Affected Areas

- [ ] Linter
- [ ] Formatter
- [ ] CLI
- [ ] Dependencies
- [ ] Documentation
- [x] Other (please specify): incremental build

## 🔗 Related Issues or PRs

Fixes #1359

### CODE REVIEW

File: crates/codex/src/populator/mod.rs [hunk 1]
```diff
@@ -121,13 +121,6 @@ fn populate_codebase_inner(
     if let Some(dirty) = &dirty_symbols {
         for dirty_key in dirty {
             if let Some(function_like_metadata) = codebase.function_likes.get_mut(dirty_key) {
-                let is_closure_or_arrow = function_like_metadata.get_kind().is_closure()
-                    || function_like_metadata.get_kind().is_arrow_function();
-
-                if is_closure_or_arrow {
-                    continue;
-                }
```
Comment (azjezz) [inline crates/codex/src/populator/mod.rs:129]: I can't remember why i did this before lol
