### PR TITLE
fix(analyzer): incorrect behavior with allow-possibly-undefined-array-keys

### LINKED ISSUE #390: bug(analyzer): allow-possibly-undefined-array-keys behaves incorrectly
### 🐞 Describe the Bug

```php
<?php

/**
 * @param array<string, int> $test
 */
function x(array $test): void
{
    if(isset($test['test'])) {
        echo $test['test'];
    }

    echo $test['test'];
}

x(['hello' => 1]);
```

in this code, mago analyze will not throw any errors, but the application will throw a warning, because 'test' doenst have to be defined in the 2nd echo

### 🔄 Steps to Reproduce

mago analyze

### ⚙️ Configuration (mago.toml)

```toml
allow-possibly-undefined-array-keys = false
```

### 📜 Command Output

```shell
> MAGO_LOG=trace mago analyze                                                                                                                                         23:10:07
DEBUG Sourcing global configuration from /home/bleksak/.config/mago.toml.
DEBUG Sourcing global configuration from /home/bleksak/mago.toml.
DEBUG Sourcing workspace configuration from /media/big_dick/dev/mago-test/mago.toml.
DEBUG Configuration specifies 16 threads.
DEBUG Configuration specifies a stack size of 12582912 bytes.
 INFO No issues found.
```

### 📂 PHP Code Sample (If Applicable)

```php

```

### 🖥️ Operating System

Linux

### 📦 How did you install Mago?

Built from Source

### 📝 Additional Context

_No response_

### PR DESCRIPTION
**Pull request by Bleksak**
## 📌 What Does This PR Do?

This PR fixes an issue when checking for an array key presence, and then accessing a different one. Mago will now properly report an error.

fixes #390 

## 🛠️ Summary of Changes

- **Bug Fix:** The analyzer will now properly report error when checking for a key presence and accessing a different one later.

## 📂 Affected Areas

- [ ] Linter
- [ ] Formatter
- [ ] CLI
- [ ] Composer Plugin
- [ ] Dependencies
- [ ] Documentation
- [x] Other (please specify): Analyzer

## 🔗 Related Issues or PRs

fixes #390

### CODE REVIEW

File: crates/analyzer/tests/cases/issue_390.php [hunk 1]
```diff
@@ -0,0 +1,13 @@
+<?php
+
+/**
+ * @param array<string, int> $test
+ * @mago-expect analysis: mixed-argument
+ * @mago-expect analysis: undefined-string-array-index
```
Comment (azjezz) [inline crates/analyzer/tests/cases/issue_390.php]:
```suggestion
 * @mago-expect analysis:mixed-argument
 * @mago-expect analysis:undefined-string-array-index
```
