### PR TITLE
fix(analyzer): recognize FQN literal constants `\true`, `\false`, `\null`

### LINKED ISSUE #1099: False positive `non-existent-constant` for `\false`, `\true`, and `\null` (fully-qualified constant access)
### Description

When using `\false`, `\true`, or `\null` (the fully-qualified form of PHP's built-in boolean/null constants), Mago reports `non-existent-constant`. These are valid PHP expressions — `\false === false` evaluates to `true` at runtime.

This is a common coding style in namespaced PHP projects. For example, [deptrac](https://github.com/qossmic/deptrac/blob/9fbc71c/src/Contract/Analyser/EventHelper.php#L31-L38) uses this pattern extensively throughout the codebase.

```php
<?php

namespace App;

$data = file_get_contents('file.txt');

if (\false === $data) {   // <-- false positive: non-existent-constant
    throw new \RuntimeException('Failed to read file');
}
```

Mago reports:

```
error[non-existent-constant]: Undefined constant: `false`.
   ┌─ src/Example.php:7:5
   │
 7 │ if (\false === $data) {
   │     ^^^^^^ Constant `false` is not defined.
```

### Playground Link

https://mago.carthage.software/playground#019c4897-dfcb-e422-e9a4-230578bb837f

### Reproduction

1\. Create a PHP file:

```php
<?php

namespace App;

function example(): void {
    $x = \false;
    $y = \true;
    $z = \null;
    var_dump($x, $y, $z);
}
```

2\. Create `mago.toml`:

```toml
[source]
paths = ["src"]
```

3\. Run:

```bash
mago analyze
```

4\. Expected: No `non-existent-constant` issues.
5\. Actual: Three `non-existent-constant` errors reported for `\false`, `\true`, and `\null`.

### Environment

- Mago: 1.7.0

### PR DESCRIPTION
**Pull request by kzmshx**
## 📌 What Does This PR Do?

Fixes a false positive where `\true`, `\false`, and `\null` (fully-qualified literal constants) were incorrectly reported as `non-existent-constant`.

## 🔍 Context & Motivation

In PHP, `\false`, `\true`, and `\null` are valid expressions equivalent to their bare forms. This is a common pattern in namespaced code to explicitly reference global constants.

## 🛠️ Summary of Changes

- Added `get_literal_constant_type()` in `mago-codex` to recognize `true`, `false`, `null` (case-insensitive).
- Updated `constant_access.rs` to check for literal constants before reporting `non-existent-constant`.
- Added `issue_1099` test case.

## 📂 Affected Areas

- [ ] Linter
- [ ] Formatter
- [ ] CLI
- [ ] Composer Plugin
- [ ] Dependencies
- [ ] Documentation
- [x] Other (please specify): Analyzer (`mago-analyzer`, `mago-codex`)

## 🔗 Related Issues or PRs

Fixes #1099

### CODE REVIEW

File: crates/codex/src/scanner/inference/mod.rs [hunk 1]
```diff
@@ -71,6 +71,25 @@ use crate::ttype::union::TUnion;
 use crate::ttype::wrap_atomic;
 use crate::utils::str_is_numeric;
 
+/// Returns the type for a predefined literal constant, if known.
+///
+/// These constants (`true`, `false`, `null`) are parsed as `Literal` nodes when bare,
+/// but become `ConstantAccess` nodes when accessed via FQN (e.g. `\true`).
+#[inline]
+pub fn get_literal_constant_type(name: &str) -> Option<TUnion> {
```
Comment (azjezz) [inline crates/codex/src/scanner/inference/mod.rs:79]: `infer` below should be updated to use this function too.

Comment (kzmshx) [reply crates/codex/src/scanner/inference/mod.rs:79]: Done in a4a82bcd.
