### PR TITLE
fix: report invalid-extend when a readonly class extends a non-readon…

### LINKED ISSUE #872: Mago should report that readonly class cannot extend non-readonly class
### Description

The playground code crashes at compile time

PHP Fatal error:  Readonly class B cannot extend non-readonly class A in /media/big_dick/dev/mago-test/src/index.php on line 7

### Playground Link

https://mago.carthage.software/playground#019bb2f0-b5eb-7f35-f607-6a2026a9bb07

### Reproduction

_No response_

### Environment

playground

### PR DESCRIPTION
**Pull request by Bleksak**
## 📌 What Does This PR Do?
fixes #872 

## 🛠️ Summary of Changes

- **Bug Fix:** Report an error when extending a readonly class with a non readonly class
 
## 🔗 Related Issues or PRs
fixes #872 

## 📝 Notes for Reviewers
:heart:

### CODE REVIEW

File: crates/analyzer/src/statement/class_like/mod.rs [hunk 1]
```diff
@@ -903,6 +903,17 @@ fn check_class_like_extends<'ctx, 'arena>(
                 );
             }
 
+            if !extended_class_metadata.flags.is_readonly() && class_like_metadata.flags.is_readonly() {
```
Comment (azjezz) [inline crates/analyzer/src/statement/class_like/mod.rs]:
```suggestion
} else if !extended_class_metadata.flags.is_readonly() && class_like_metadata.flags.is_readonly() {
```

Comment (Bleksak) [reply crates/analyzer/src/statement/class_like/mod.rs]: fixed
